package br.com.locadora.modelo;

// Generated 08/09/2014 17:04:12 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * DescontoLocacao generated by hbm2java
 */
@Audited
@Entity
@Table(name = "DESCONTO_LOCACAO", catalog = "renovarsistemas")
@AuditTable(value="DESCONTO_LOCACAO", schema="log", catalog="renovarsistemas")
public class DescontoLocacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4990275384410407330L;
	private int descLocId;
	private Locacao locacao;
	private Date descLocInicio;
	private Date descLocFim;
	private Double descLocValor;

	public DescontoLocacao() {
	}

	public DescontoLocacao(int descLocId, Locacao locacao) {
		this.descLocId = descLocId;
		this.locacao = locacao;
	}

	public DescontoLocacao(int descLocId, Locacao locacao, Date descLocInicio,
			Date descLocFim, Double descLocValor) {
		this.descLocId = descLocId;
		this.locacao = locacao;
		this.descLocInicio = descLocInicio;
		this.descLocFim = descLocFim;
		this.descLocValor = descLocValor;
	}

	@Id
	@GeneratedValue
	@Column(name = "DESC_LOC_ID", unique = true, nullable = false)
	public int getDescLocId() {
		return this.descLocId;
	}

	public void setDescLocId(int descLocId) {
		this.descLocId = descLocId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOC_ID", nullable = false)
	public Locacao getLocacao() {
		return this.locacao;
	}

	public void setLocacao(Locacao locacao) {
		this.locacao = locacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DESC_LOC_INICIO", length = 23)
	public Date getDescLocInicio() {
		return this.descLocInicio;
	}

	public void setDescLocInicio(Date descLocInicio) {
		this.descLocInicio = descLocInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DESC_LOC_FIM", length = 23)
	public Date getDescLocFim() {
		return this.descLocFim;
	}

	public void setDescLocFim(Date descLocFim) {
		this.descLocFim = descLocFim;
	}

	@Column(name = "DESC_LOC_VALOR", precision = 53, scale = 0)
	public Double getDescLocValor() {
		return this.descLocValor;
	}

	public void setDescLocValor(Double descLocValor) {
		this.descLocValor = descLocValor;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((descLocFim == null) ? 0 : descLocFim.hashCode());
		result = prime * result + descLocId;
		result = prime * result
				+ ((descLocInicio == null) ? 0 : descLocInicio.hashCode());
		result = prime * result
				+ ((descLocValor == null) ? 0 : descLocValor.hashCode());
		result = prime * result + ((locacao == null) ? 0 : locacao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DescontoLocacao other = (DescontoLocacao) obj;
		if (descLocFim == null) {
			if (other.descLocFim != null)
				return false;
		} else if (!descLocFim.equals(other.descLocFim))
			return false;
		if (descLocId != other.descLocId)
			return false;
		if (descLocInicio == null) {
			if (other.descLocInicio != null)
				return false;
		} else if (!descLocInicio.equals(other.descLocInicio))
			return false;
		if (descLocValor == null) {
			if (other.descLocValor != null)
				return false;
		} else if (!descLocValor.equals(other.descLocValor))
			return false;
		if (locacao == null) {
			if (other.locacao != null)
				return false;
		} else if (!locacao.equals(other.locacao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "DescontoLocacao [descLocId=" + descLocId + "]";
	}

}
