package br.com.locadora.modelo;

// Generated 03/07/2014 08:40:10 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * ImpostoDeRenda generated by hbm2java
 */
@Audited
@Entity
@Table(name = "IMPOSTO_DE_RENDA", catalog = "renovarsistemas")
@AuditTable(value="IMPOSTO_DE_RENDA", schema="log", catalog="renovarsistemas")
public class ImpostoDeRenda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7794953199912660443L;
	private int impRenId;
	private Integer impRenMes;
	private Integer impRenAno;
	private List<FaixaImpostoDeRenda> faixaImpostoDeRendas = new ArrayList<FaixaImpostoDeRenda>(
			0);

	public ImpostoDeRenda() {
	}

	public ImpostoDeRenda(int impRenId) {
		this.impRenId = impRenId;
	}

	public ImpostoDeRenda(int impRenId, Integer impRenMes, Integer impRenAno,
			List<FaixaImpostoDeRenda> faixaImpostoDeRendas) {
		this.impRenId = impRenId;
		this.impRenMes = impRenMes;
		this.impRenAno = impRenAno;
		this.faixaImpostoDeRendas = faixaImpostoDeRendas;
	}

	@Id
	@GeneratedValue
	@Column(name = "IMP_REN_ID", unique = true, nullable = false)
	public int getImpRenId() {
		return this.impRenId;
	}

	public void setImpRenId(int impRenId) {
		this.impRenId = impRenId;
	}

	@Column(name = "IMP_REN_MES")
	public Integer getImpRenMes() {
		return this.impRenMes;
	}

	public void setImpRenMes(Integer impRenMes) {
		this.impRenMes = impRenMes;
	}

	@Column(name = "IMP_REN_ANO")
	public Integer getImpRenAno() {
		return this.impRenAno;
	}

	public void setImpRenAno(Integer impRenAno) {
		this.impRenAno = impRenAno;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "impostoDeRenda")
	@NotAudited
	public List<FaixaImpostoDeRenda> getFaixaImpostoDeRendas() {
		return this.faixaImpostoDeRendas;
	}

	public void setFaixaImpostoDeRendas(
			List<FaixaImpostoDeRenda> faixaImpostoDeRendas) {
		this.faixaImpostoDeRendas = faixaImpostoDeRendas;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((faixaImpostoDeRendas == null) ? 0 : faixaImpostoDeRendas
						.hashCode());
		result = prime * result
				+ ((impRenAno == null) ? 0 : impRenAno.hashCode());
		result = prime * result + impRenId;
		result = prime * result
				+ ((impRenMes == null) ? 0 : impRenMes.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ImpostoDeRenda other = (ImpostoDeRenda) obj;
		if (faixaImpostoDeRendas == null) {
			if (other.faixaImpostoDeRendas != null)
				return false;
		} else if (!faixaImpostoDeRendas.equals(other.faixaImpostoDeRendas))
			return false;
		if (impRenAno == null) {
			if (other.impRenAno != null)
				return false;
		} else if (!impRenAno.equals(other.impRenAno))
			return false;
		if (impRenId != other.impRenId)
			return false;
		if (impRenMes == null) {
			if (other.impRenMes != null)
				return false;
		} else if (!impRenMes.equals(other.impRenMes))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ImpostoDeRenda [impRenId=" + impRenId + "]";
	}

}
