package br.com.locadora.modelo;

// Generated 19/06/2014 08:15:40 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * InformacaoAdicional generated by hbm2java
 */
@Audited
@Entity
@Table(name = "INFORMACAO_ADICIONAL", catalog = "renovarsistemas")
@AuditTable(value="INFORMACAO_ADICIONAL", schema="log", catalog="renovarsistemas")
public class InformacaoAdicional implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5658569108926609933L;
	private int infAdiId;
	private Locacao locacao;
	private Date infAdiData;
	private String infAdiSetor;
	private Integer infAdiFuncionario;
	private String infAdiObservacao;

	public InformacaoAdicional() {
	}

	public InformacaoAdicional(int infAdiId) {
		this.infAdiId = infAdiId;
	}

	public InformacaoAdicional(int infAdiId, Locacao locacao, Date infAdiData,
			String infAdiSetor, Integer infAdiFuncionario,
			String infAdiObservacao) {
		this.infAdiId = infAdiId;
		this.locacao = locacao;
		this.infAdiData = infAdiData;
		this.infAdiSetor = infAdiSetor;
		this.infAdiFuncionario = infAdiFuncionario;
		this.infAdiObservacao = infAdiObservacao;
	}

	@Id
	@GeneratedValue
	@Column(name = "INF_ADI_ID", unique = true, nullable = false)
	public int getInfAdiId() {
		return this.infAdiId;
	}

	public void setInfAdiId(int infAdiId) {
		this.infAdiId = infAdiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOC_ID")
	public Locacao getLocacao() {
		return this.locacao;
	}

	public void setLocacao(Locacao locacao) {
		this.locacao = locacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INF_ADI_DATA", length = 23)
	public Date getInfAdiData() {
		return this.infAdiData;
	}

	public void setInfAdiData(Date infAdiData) {
		this.infAdiData = infAdiData;
	}

	@Column(name = "INF_ADI_SETOR", length = 60)
	public String getInfAdiSetor() {
		return this.infAdiSetor;
	}

	public void setInfAdiSetor(String infAdiSetor) {
		this.infAdiSetor = infAdiSetor;
	}

	@Column(name = "INF_ADI_FUNCIONARIO")
	public Integer getInfAdiFuncionario() {
		return this.infAdiFuncionario;
	}

	public void setInfAdiFuncionario(Integer infAdiFuncionario) {
		this.infAdiFuncionario = infAdiFuncionario;
	}

	@Column(name = "INF_ADI_OBSERVACAO", length = 251)
	public String getInfAdiObservacao() {
		return this.infAdiObservacao;
	}

	public void setInfAdiObservacao(String infAdiObservacao) {
		this.infAdiObservacao = infAdiObservacao;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((infAdiData == null) ? 0 : infAdiData.hashCode());
		result = prime
				* result
				+ ((infAdiFuncionario == null) ? 0 : infAdiFuncionario
						.hashCode());
		result = prime * result + infAdiId;
		result = prime
				* result
				+ ((infAdiObservacao == null) ? 0 : infAdiObservacao.hashCode());
		result = prime * result
				+ ((infAdiSetor == null) ? 0 : infAdiSetor.hashCode());
		result = prime * result + ((locacao == null) ? 0 : locacao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		InformacaoAdicional other = (InformacaoAdicional) obj;
		if (infAdiData == null) {
			if (other.infAdiData != null)
				return false;
		} else if (!infAdiData.equals(other.infAdiData))
			return false;
		if (infAdiFuncionario == null) {
			if (other.infAdiFuncionario != null)
				return false;
		} else if (!infAdiFuncionario.equals(other.infAdiFuncionario))
			return false;
		if (infAdiId != other.infAdiId)
			return false;
		if (infAdiObservacao == null) {
			if (other.infAdiObservacao != null)
				return false;
		} else if (!infAdiObservacao.equals(other.infAdiObservacao))
			return false;
		if (infAdiSetor == null) {
			if (other.infAdiSetor != null)
				return false;
		} else if (!infAdiSetor.equals(other.infAdiSetor))
			return false;
		if (locacao == null) {
			if (other.locacao != null)
				return false;
		} else if (!locacao.equals(other.locacao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "InformacaoAdicional [infAdiId=" + infAdiId + "]";
	}

}
