package br.com.locadora.modelo;

// Generated 15/09/2014 11:39:54 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * LancamentoContasAPagar generated by hbm2java
 */
@Audited
@Entity
@Table(name = "LANCAMENTO_CONTAS_A_PAGAR", catalog = "renovarsistemas")
@AuditTable(value="LANCAMENTO_CONTAS_A_PAGAR", schema="log", catalog="renovarsistemas")
public class LancamentoContasAPagar implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4617244980734047184L;
	private int lanConPagId;
	private ContasAPagar contasAPagar;
	private Date lanConPagDataCadastro;
	private Integer lanConPagIdContaCorrente;

	public LancamentoContasAPagar() {
	}

	public LancamentoContasAPagar(int lanConPagId, ContasAPagar contasAPagar) {
		this.lanConPagId = lanConPagId;
		this.contasAPagar = contasAPagar;
	}

	public LancamentoContasAPagar(int lanConPagId, ContasAPagar contasAPagar,
			Date lanConPagDataCadastro, Integer lanConPagIdContaCorrente) {
		this.lanConPagId = lanConPagId;
		this.contasAPagar = contasAPagar;
		this.lanConPagDataCadastro = lanConPagDataCadastro;
		this.lanConPagIdContaCorrente = lanConPagIdContaCorrente;
	}

	@Id
	@GeneratedValue
	@Column(name = "LAN_CON_PAG_ID", unique = true, nullable = false)
	public int getLanConPagId() {
		return this.lanConPagId;
	}

	public void setLanConPagId(int lanConPagId) {
		this.lanConPagId = lanConPagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_PAG_ID", nullable = false)
	public ContasAPagar getContasAPagar() {
		return this.contasAPagar;
	}

	public void setContasAPagar(ContasAPagar contasAPagar) {
		this.contasAPagar = contasAPagar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAN_CON_PAG_DATA_CADASTRO", length = 23)
	public Date getLanConPagDataCadastro() {
		return this.lanConPagDataCadastro;
	}

	public void setLanConPagDataCadastro(Date lanConPagDataCadastro) {
		this.lanConPagDataCadastro = lanConPagDataCadastro;
	}

	@Column(name = "LAN_CON_PAG_ID_CONTA_CORRENTE")
	public Integer getLanConPagIdContaCorrente() {
		return this.lanConPagIdContaCorrente;
	}

	public void setLanConPagIdContaCorrente(Integer lanConPagIdContaCorrente) {
		this.lanConPagIdContaCorrente = lanConPagIdContaCorrente;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((contasAPagar == null) ? 0 : contasAPagar.hashCode());
		result = prime
				* result
				+ ((lanConPagDataCadastro == null) ? 0 : lanConPagDataCadastro
						.hashCode());
		result = prime * result + lanConPagId;
		result = prime
				* result
				+ ((lanConPagIdContaCorrente == null) ? 0
						: lanConPagIdContaCorrente.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LancamentoContasAPagar other = (LancamentoContasAPagar) obj;
		if (contasAPagar == null) {
			if (other.contasAPagar != null)
				return false;
		} else if (!contasAPagar.equals(other.contasAPagar))
			return false;
		if (lanConPagDataCadastro == null) {
			if (other.lanConPagDataCadastro != null)
				return false;
		} else if (!lanConPagDataCadastro.equals(other.lanConPagDataCadastro))
			return false;
		if (lanConPagId != other.lanConPagId)
			return false;
		if (lanConPagIdContaCorrente == null) {
			if (other.lanConPagIdContaCorrente != null)
				return false;
		} else if (!lanConPagIdContaCorrente
				.equals(other.lanConPagIdContaCorrente))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "LancamentoContasAPagar [lanConPagId=" + lanConPagId + "]";
	}

}
