package br.com.locadora.modelo;

// Generated 30/04/2014 13:20:46 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * PessoaFiador generated by hbm2java
 */
@Audited
@Entity
@Table(name = "PESSOA_FIADOR", catalog = "renovarsistemas")
@AuditTable(value="PESSOA_FIADOR", schema="log", catalog="renovarsistemas")
public class PessoaFiador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7763335674472983297L;
	private PessoaFiadorId id;
	private Pessoa pessoa;
	private Fiador fiador;

	public PessoaFiador() {
	}

	public PessoaFiador(PessoaFiadorId id) {
		this.id = id;
	}

	public PessoaFiador(PessoaFiadorId id, Pessoa pessoa, Fiador fiador) {
		this.id = id;
		this.pessoa = pessoa;
		this.fiador = fiador;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fiaId", column = @Column(name = "FIA_ID")),
			@AttributeOverride(name = "pesId", column = @Column(name = "PES_ID")) })
	public PessoaFiadorId getId() {
		return this.id;
	}

	public void setId(PessoaFiadorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PES_ID", insertable = false, updatable = false)
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIA_ID", insertable = false, updatable = false)
	public Fiador getFiador() {
		return this.fiador;
	}

	public void setFiador(Fiador fiador) {
		this.fiador = fiador;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fiador == null) ? 0 : fiador.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((pessoa == null) ? 0 : pessoa.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PessoaFiador other = (PessoaFiador) obj;
		if (fiador == null) {
			if (other.fiador != null)
				return false;
		} else if (!fiador.equals(other.fiador))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (pessoa == null) {
			if (other.pessoa != null)
				return false;
		} else if (!pessoa.equals(other.pessoa))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "PessoaFiador [id=" + id + "]";
	}

}
