package br.com.locadora.modelo;

// Generated 10/07/2014 16:00:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * PlanoDeContas generated by hbm2java
 */
@Audited
@Entity
@Table(name = "PLANO_DE_CONTAS", catalog = "renovarsistemas")
@AuditTable(value="PLANO_DE_CONTAS", schema="log", catalog="renovarsistemas")
public class PlanoDeContas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6798043273329649093L;
	private int plaConId;
	private String plaConNome;
	private Boolean plaConCredito;
	private Boolean plaConDebito;
	private Set<GrupoDeContas> grupoContasJuros = new HashSet<GrupoDeContas>(0);
	private Set<GrupoDeContas> grupoContasMultas = new HashSet<GrupoDeContas>(0);
	private Set<GrupoDeContas> grupoContasValorOriginal = new HashSet<GrupoDeContas>(0);

	public PlanoDeContas() {
	}

	public PlanoDeContas(int plaConId) {
		this.plaConId = plaConId;
	}

	public PlanoDeContas(int plaConId, String plaConNome,
			Boolean plaConCredito, Boolean plaConDebito,
			Set<GrupoDeContas> grupoContasJuros,
			Set<GrupoDeContas> grupoContasMultas,
			Set<GrupoDeContas> grupoContasValorOriginal) {
		this.plaConId = plaConId;
		this.plaConNome = plaConNome;
		this.plaConCredito = plaConCredito;
		this.plaConDebito = plaConDebito;
		this.grupoContasJuros = grupoContasJuros;
		this.grupoContasMultas = grupoContasMultas;
		this.grupoContasValorOriginal = grupoContasValorOriginal;
	}

	@Id
	@GeneratedValue
	@Column(name = "PLA_CON_ID", unique = true, nullable = false)
	public int getPlaConId() {
		return this.plaConId;
	}

	public void setPlaConId(int plaConId) {
		this.plaConId = plaConId;
	}

	@Column(name = "PLA_CON_NOME", length = 60)
	public String getPlaConNome() {
		return this.plaConNome;
	}

	public void setPlaConNome(String plaConNome) {
		this.plaConNome = plaConNome;
	}

	@Column(name = "PLA_CON_CREDITO")
	public Boolean getPlaConCredito() {
		return this.plaConCredito;
	}

	public void setPlaConCredito(Boolean plaConCredito) {
		this.plaConCredito = plaConCredito;
	}

	@Column(name = "PLA_CON_DEBITO")
	public Boolean getPlaConDebito() {
		return this.plaConDebito;
	}

	public void setPlaConDebito(Boolean plaConDebito) {
		this.plaConDebito = plaConDebito;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "grupoContasJuros")
	public Set<GrupoDeContas> getGrupoContasJuros() {
		return this.grupoContasJuros;
	}

	public void setGrupoContasJuros(Set<GrupoDeContas> grupoContasJuros) {
		this.grupoContasJuros = grupoContasJuros;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "grupoContasMultas")
	public Set<GrupoDeContas> getGrupoContasMultas() {
		return this.grupoContasMultas;
	}

	public void setGrupoContasMultas(Set<GrupoDeContas> grupoContasMultas) {
		this.grupoContasMultas = grupoContasMultas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "grupoContasValorOriginal")
	public Set<GrupoDeContas> getGrupoContasValorOriginal() {
		return this.grupoContasValorOriginal;
	}

	public void setGrupoContasValorOriginal(Set<GrupoDeContas> grupoContasValorOriginal) {
		this.grupoContasValorOriginal = grupoContasValorOriginal;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((grupoContasJuros == null) ? 0 : grupoContasJuros.hashCode());
		result = prime
				* result
				+ ((grupoContasMultas == null) ? 0 : grupoContasMultas
						.hashCode());
		result = prime
				* result
				+ ((grupoContasValorOriginal == null) ? 0
						: grupoContasValorOriginal.hashCode());
		result = prime * result
				+ ((plaConCredito == null) ? 0 : plaConCredito.hashCode());
		result = prime * result
				+ ((plaConDebito == null) ? 0 : plaConDebito.hashCode());
		result = prime * result + plaConId;
		result = prime * result
				+ ((plaConNome == null) ? 0 : plaConNome.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PlanoDeContas other = (PlanoDeContas) obj;
		if (grupoContasJuros == null) {
			if (other.grupoContasJuros != null)
				return false;
		} else if (!grupoContasJuros.equals(other.grupoContasJuros))
			return false;
		if (grupoContasMultas == null) {
			if (other.grupoContasMultas != null)
				return false;
		} else if (!grupoContasMultas.equals(other.grupoContasMultas))
			return false;
		if (grupoContasValorOriginal == null) {
			if (other.grupoContasValorOriginal != null)
				return false;
		} else if (!grupoContasValorOriginal
				.equals(other.grupoContasValorOriginal))
			return false;
		if (plaConCredito == null) {
			if (other.plaConCredito != null)
				return false;
		} else if (!plaConCredito.equals(other.plaConCredito))
			return false;
		if (plaConDebito == null) {
			if (other.plaConDebito != null)
				return false;
		} else if (!plaConDebito.equals(other.plaConDebito))
			return false;
		if (plaConId != other.plaConId)
			return false;
		if (plaConNome == null) {
			if (other.plaConNome != null)
				return false;
		} else if (!plaConNome.equals(other.plaConNome))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "PlanoDeContas [plaConId=" + plaConId + "]";
	}

}
