package br.com.locadora.modelo;

// Generated 01/07/2014 15:25:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * ProprietariosLocacao generated by hbm2java
 */
@Audited
@Entity
@Table(name = "PROPRIETARIOS_LOCACAO", catalog = "renovarsistemas")
@AuditTable(value="PROPRIETARIOS_LOCACAO", schema="log", catalog="renovarsistemas")
public class ProprietariosLocacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4437500165242166158L;
	private int proLocId;
	private Locacao locacao;
	private Integer proLocIdpessoa;
	private Integer proLocIdimovel;

	public ProprietariosLocacao() {
	}

	public ProprietariosLocacao(int proLocId, Locacao locacao) {
		this.proLocId = proLocId;
		this.locacao = locacao;
	}

	public ProprietariosLocacao(int proLocId, Locacao locacao,
			Integer proLocIdpessoa, Integer proLocIdimovel) {
		this.proLocId = proLocId;
		this.locacao = locacao;
		this.proLocIdpessoa = proLocIdpessoa;
		this.proLocIdimovel = proLocIdimovel;
	}

	@Id
	@GeneratedValue
	@Column(name = "PRO_LOC_ID", unique = true, nullable = false)
	public int getProLocId() {
		return this.proLocId;
	}

	public void setProLocId(int proLocId) {
		this.proLocId = proLocId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOC_ID", nullable = false)
	public Locacao getLocacao() {
		return this.locacao;
	}

	public void setLocacao(Locacao locacao) {
		this.locacao = locacao;
	}

	@Column(name = "PRO_LOC_IDPESSOA")
	public Integer getProLocIdpessoa() {
		return this.proLocIdpessoa;
	}

	public void setProLocIdpessoa(Integer proLocIdpessoa) {
		this.proLocIdpessoa = proLocIdpessoa;
	}

	@Column(name = "PRO_LOC_IDIMOVEL")
	public Integer getProLocIdimovel() {
		return this.proLocIdimovel;
	}

	public void setProLocIdimovel(Integer proLocIdimovel) {
		this.proLocIdimovel = proLocIdimovel;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((locacao == null) ? 0 : locacao.hashCode());
		result = prime * result + proLocId;
		result = prime * result
				+ ((proLocIdimovel == null) ? 0 : proLocIdimovel.hashCode());
		result = prime * result
				+ ((proLocIdpessoa == null) ? 0 : proLocIdpessoa.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProprietariosLocacao other = (ProprietariosLocacao) obj;
		if (locacao == null) {
			if (other.locacao != null)
				return false;
		} else if (!locacao.equals(other.locacao))
			return false;
		if (proLocId != other.proLocId)
			return false;
		if (proLocIdimovel == null) {
			if (other.proLocIdimovel != null)
				return false;
		} else if (!proLocIdimovel.equals(other.proLocIdimovel))
			return false;
		if (proLocIdpessoa == null) {
			if (other.proLocIdpessoa != null)
				return false;
		} else if (!proLocIdpessoa.equals(other.proLocIdpessoa))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ProprietariosLocacao [proLocId=" + proLocId + "]";
	}

}
