package br.com.locadora.modelo;

// Generated 07/07/2014 09:57:49 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * SeguroIncendio generated by hbm2java
 */
@Audited
@Entity
@Table(name = "SEGURO_INCENDIO", catalog = "renovarsistemas")
@AuditTable(value="SEGURO_INCENDIO", schema="log", catalog="renovarsistemas")
public class SeguroIncendio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6741555733912060470L;
	private int segIncId;
	private Locacao locacao;
	private String segIncSeguradora;
	private String segIncApolice;
	private Date segIncDataInicio;
	private Date segIncDataFinal;
	private Double segIncValorTotal;
	private Double segIncValorVenalTotal;
	private Integer segIncPlano;
	private String segIncProposta;
	private Double segIncValorParcela;
	private Boolean segIncSeguroParticular;
	private Boolean segIncSeguroEspecial;
	private Set<Locacao> locacaos = new HashSet<Locacao>(0);

	public SeguroIncendio() {
	}

	public SeguroIncendio(int segIncId, Locacao locacao) {
		this.segIncId = segIncId;
		this.locacao = locacao;
	}

	public SeguroIncendio(int segIncId, Locacao locacao,
			String segIncSeguradora, String segIncApolice,
			Date segIncDataInicio, Date segIncDataFinal,String segFiaProposta,
			Double segIncValorTotal, Double segIncValorVenalTotal,Boolean segIncSeguroParticular,Boolean segIncSeguroEspecial,
			Integer segIncPlano, Double segIncValorParcela, Set<Locacao> locacaos) {
		this.segIncId = segIncId;
		this.locacao = locacao;
		this.segIncSeguradora = segIncSeguradora;
		this.segIncApolice = segIncApolice;
		this.segIncDataInicio = segIncDataInicio;
		this.segIncDataFinal = segIncDataFinal;
		this.segIncValorTotal = segIncValorTotal;
		this.segIncValorVenalTotal = segIncValorVenalTotal;
		this.segIncPlano = segIncPlano;
		this.segIncProposta = segFiaProposta;
		this.segIncSeguroParticular=segIncSeguroParticular;
		this.segIncValorParcela = segIncValorParcela;
		this.segIncSeguroEspecial=segIncSeguroEspecial;
		this.locacaos = locacaos;
	}

	@Id
	@GeneratedValue
	@Column(name = "SEG_INC_ID", unique = true, nullable = false)
	public int getSegIncId() {
		return this.segIncId;
	}

	public void setSegIncId(int segIncId) {
		this.segIncId = segIncId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOC_ID", nullable = false)
	public Locacao getLocacao() {
		return this.locacao;
	}

	public void setLocacao(Locacao locacao) {
		this.locacao = locacao;
	}

	@Column(name = "SEG_INC_SEGURADORA", length = 60)
	public String getSegIncSeguradora() {
		return this.segIncSeguradora;
	}

	public void setSegIncSeguradora(String segIncSeguradora) {
		this.segIncSeguradora = segIncSeguradora;
	}

	@Column(name = "SEG_INC_APOLICE", length = 60)
	public String getSegIncApolice() {
		return this.segIncApolice;
	}

	public void setSegIncApolice(String segIncApolice) {
		this.segIncApolice = segIncApolice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SEG_INC_DATA_INICIO", length = 23)
	public Date getSegIncDataInicio() {
		return this.segIncDataInicio;
	}

	public void setSegIncDataInicio(Date segIncDataInicio) {
		this.segIncDataInicio = segIncDataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SEG_INC_DATA_FINAL", length = 23)
	public Date getSegIncDataFinal() {
		return this.segIncDataFinal;
	}

	public void setSegIncDataFinal(Date segIncDataFinal) {
		this.segIncDataFinal = segIncDataFinal;
	}

	@Column(name = "SEG_INC_VALOR_TOTAL", precision = 53, scale = 0)
	public Double getSegIncValorTotal() {
		return this.segIncValorTotal;
	}

	public void setSegIncValorTotal(Double segIncValorTotal) {
		this.segIncValorTotal = segIncValorTotal;
	}
	@Column(name = "SEG_INC_SEGURO_PARTICULAR")
	public Boolean getSegIncSeguroParticular() {
		return segIncSeguroParticular;
	}

	public void setSegIncSeguroParticular(Boolean segIncSeguroParticular) {
		this.segIncSeguroParticular = segIncSeguroParticular;
	}
	@Column(name = "SEG_INC_SEGURO_ESPECIAL")
	public Boolean getSegIncSeguroEspecial() {
		return segIncSeguroEspecial;
	}

	public void setSegIncSeguroEspecial(Boolean segIncSeguroEspecial) {
		this.segIncSeguroEspecial = segIncSeguroEspecial;
	}

	@Column(name = "SEG_INC_VALOR_VENAL_TOTAL", precision = 53, scale = 0)
	public Double getSegIncValorVenalTotal() {
		return this.segIncValorVenalTotal;
	}

	public void setSegIncValorVenalTotal(Double segIncValorVenalTotal) {
		this.segIncValorVenalTotal = segIncValorVenalTotal;
	}
	
	@Column(name = "SEG_INC_PROPOSTA", length = 60)
	public String getSegIncProposta() {
		return this.segIncProposta;
	}

	public void setSegIncProposta(String segFiaProposta) {
		this.segIncProposta = segFiaProposta;
	}
	
	@Column(name = "SEG_INC_PLANO_")
	public Integer getSegIncPlano() {
		return this.segIncPlano;
	}

	public void setSegIncPlano(Integer segIncPlano) {
		this.segIncPlano = segIncPlano;
	}

	@Column(name = "SEG_INC_VALOR_PARCELA", precision = 53, scale = 0)
	public Double getSegIncValorParcela() {
		return this.segIncValorParcela;
	}

	public void setSegIncValorParcela(Double segIncValorParcela) {
		this.segIncValorParcela = segIncValorParcela;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seguroIncendio")
	@NotAudited
	public Set<Locacao> getLocacaos() {
		return this.locacaos;
	}

	public void setLocacaos(Set<Locacao> locacaos) {
		this.locacaos = locacaos;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((locacao == null) ? 0 : locacao.hashCode());
		result = prime * result
				+ ((locacaos == null) ? 0 : locacaos.hashCode());
		result = prime * result
				+ ((segIncApolice == null) ? 0 : segIncApolice.hashCode());
		result = prime * result
				+ ((segIncDataFinal == null) ? 0 : segIncDataFinal.hashCode());
		result = prime
				* result
				+ ((segIncDataInicio == null) ? 0 : segIncDataInicio.hashCode());
		result = prime * result + segIncId;
		result = prime * result
				+ ((segIncPlano == null) ? 0 : segIncPlano.hashCode());
		result = prime * result
				+ ((segIncProposta == null) ? 0 : segIncProposta.hashCode());
		result = prime
				* result
				+ ((segIncSeguradora == null) ? 0 : segIncSeguradora.hashCode());
		result = prime
				* result
				+ ((segIncSeguroEspecial == null) ? 0 : segIncSeguroEspecial
						.hashCode());
		result = prime
				* result
				+ ((segIncSeguroParticular == null) ? 0
						: segIncSeguroParticular.hashCode());
		result = prime
				* result
				+ ((segIncValorParcela == null) ? 0 : segIncValorParcela
						.hashCode());
		result = prime
				* result
				+ ((segIncValorTotal == null) ? 0 : segIncValorTotal.hashCode());
		result = prime
				* result
				+ ((segIncValorVenalTotal == null) ? 0 : segIncValorVenalTotal
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SeguroIncendio other = (SeguroIncendio) obj;
		if (locacao == null) {
			if (other.locacao != null)
				return false;
		} else if (!locacao.equals(other.locacao))
			return false;
		if (locacaos == null) {
			if (other.locacaos != null)
				return false;
		} else if (!locacaos.equals(other.locacaos))
			return false;
		if (segIncApolice == null) {
			if (other.segIncApolice != null)
				return false;
		} else if (!segIncApolice.equals(other.segIncApolice))
			return false;
		if (segIncDataFinal == null) {
			if (other.segIncDataFinal != null)
				return false;
		} else if (!segIncDataFinal.equals(other.segIncDataFinal))
			return false;
		if (segIncDataInicio == null) {
			if (other.segIncDataInicio != null)
				return false;
		} else if (!segIncDataInicio.equals(other.segIncDataInicio))
			return false;
		if (segIncId != other.segIncId)
			return false;
		if (segIncPlano == null) {
			if (other.segIncPlano != null)
				return false;
		} else if (!segIncPlano.equals(other.segIncPlano))
			return false;
		if (segIncProposta == null) {
			if (other.segIncProposta != null)
				return false;
		} else if (!segIncProposta.equals(other.segIncProposta))
			return false;
		if (segIncSeguradora == null) {
			if (other.segIncSeguradora != null)
				return false;
		} else if (!segIncSeguradora.equals(other.segIncSeguradora))
			return false;
		if (segIncSeguroEspecial == null) {
			if (other.segIncSeguroEspecial != null)
				return false;
		} else if (!segIncSeguroEspecial.equals(other.segIncSeguroEspecial))
			return false;
		if (segIncSeguroParticular == null) {
			if (other.segIncSeguroParticular != null)
				return false;
		} else if (!segIncSeguroParticular.equals(other.segIncSeguroParticular))
			return false;
		if (segIncValorParcela == null) {
			if (other.segIncValorParcela != null)
				return false;
		} else if (!segIncValorParcela.equals(other.segIncValorParcela))
			return false;
		if (segIncValorTotal == null) {
			if (other.segIncValorTotal != null)
				return false;
		} else if (!segIncValorTotal.equals(other.segIncValorTotal))
			return false;
		if (segIncValorVenalTotal == null) {
			if (other.segIncValorVenalTotal != null)
				return false;
		} else if (!segIncValorVenalTotal.equals(other.segIncValorVenalTotal))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "SeguroIncendio [segIncId=" + segIncId + "]";
	}

}
