package br.com.locadora.modelo;

// Generated 26/06/2014 17:19:33 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SituacaoLocacaoPermissoesId generated by hbm2java
 */
@Embeddable
public class SituacaoLocacaoPermissoesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4077462849484664957L;
	private int perLocId;
	private int sitLocId;

	public SituacaoLocacaoPermissoesId() {
	}

	public SituacaoLocacaoPermissoesId(int perLocId, int sitLocId) {
		this.perLocId = perLocId;
		this.sitLocId = sitLocId;
	}

	@Column(name = "PER_LOC_ID", nullable = false)
	public int getPerLocId() {
		return this.perLocId;
	}

	public void setPerLocId(int perLocId) {
		this.perLocId = perLocId;
	}

	@Column(name = "SIT_LOC_ID", nullable = false)
	public int getSitLocId() {
		return this.sitLocId;
	}

	public void setSitLocId(int sitLocId) {
		this.sitLocId = sitLocId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SituacaoLocacaoPermissoesId))
			return false;
		SituacaoLocacaoPermissoesId castOther = (SituacaoLocacaoPermissoesId) other;

		return (this.getPerLocId() == castOther.getPerLocId())
				&& (this.getSitLocId() == castOther.getSitLocId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPerLocId();
		result = 37 * result + this.getSitLocId();
		return result;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "SituacaoLocacaoPermissoesId [perLocId=" + perLocId + "]";
	}

}
