package br.com.locadora.modelo;

// Generated 14/05/2014 10:34:22 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProprietarioId generated by hbm2java
 */
@Embeddable
public class ProprietarioId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8707341887221492322L;
	private int imoId;
	private int pesId;

	public ProprietarioId() {
	}

	public ProprietarioId(int imoId, int pesId) {
		this.imoId = imoId;
		this.pesId = pesId;
	}

	@Column(name = "IMO_ID", nullable = false)
	public int getImoId() {
		return this.imoId;
	}

	public void setImoId(int imoId) {
		this.imoId = imoId;
	}

	@Column(name = "PES_ID", nullable = false)
	public int getPesId() {
		return this.pesId;
	}

	public void setPesId(int pesId) {
		this.pesId = pesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProprietarioId))
			return false;
		ProprietarioId castOther = (ProprietarioId) other;

		return (this.getImoId() == castOther.getImoId())
				&& (this.getPesId() == castOther.getPesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImoId();
		result = 37 * result + this.getPesId();
		return result;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "ProprietarioId [imoId=" + imoId + ", pesId=" + pesId + "]";
	}

}
