package br.com.locadora.modelo;

// Generated 11/04/2014 14:12:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * Ramoatuacao generated by hbm2java
 */
@Audited
@Entity
@Table(name = "RAMOATUACAO", catalog = "renovarsistemas")
@AuditTable(value="RAMOATUACAO", schema="log", catalog="renovarsistemas")
public class Ramoatuacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5995589924258246631L;
	private int ramId;
	private String ramNome;
	private String ramObservacao;
	private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

	public Ramoatuacao() {
	}

	public Ramoatuacao(int ramId, String ramNome) {
		this.ramId = ramId;
		this.ramNome = ramNome;
	}

	public Ramoatuacao(int ramId, String ramNome, String ramObservacao,
			Set<Pessoa> pessoas) {
		this.ramId = ramId;
		this.ramNome = ramNome;
		this.ramObservacao = ramObservacao;
		this.pessoas = pessoas;
	}

	@Id
	@GeneratedValue
	@Column(name = "RAM_ID", unique = true, nullable = false)
	public int getRamId() {
		return this.ramId;
	}

	public void setRamId(int ramId) {
		this.ramId = ramId;
	}

	@Column(name = "RAM_NOME", nullable = false, length = 50)
	public String getRamNome() {
		return this.ramNome;
	}

	public void setRamNome(String ramNome) {
		this.ramNome = ramNome;
	}

	@Column(name = "RAM_OBSERVACAO", length = 150)
	public String getRamObservacao() {
		return this.ramObservacao;
	}

	public void setRamObservacao(String ramObservacao) {
		this.ramObservacao = ramObservacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ramoatuacao")
	@NotAudited
	public Set<Pessoa> getPessoas() {
		return this.pessoas;
	}

	public void setPessoas(Set<Pessoa> pessoas) {
		this.pessoas = pessoas;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pessoas == null) ? 0 : pessoas.hashCode());
		result = prime * result + ramId;
		result = prime * result + ((ramNome == null) ? 0 : ramNome.hashCode());
		result = prime * result
				+ ((ramObservacao == null) ? 0 : ramObservacao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Ramoatuacao other = (Ramoatuacao) obj;
		if (pessoas == null) {
			if (other.pessoas != null)
				return false;
		} else if (!pessoas.equals(other.pessoas))
			return false;
		if (ramId != other.ramId)
			return false;
		if (ramNome == null) {
			if (other.ramNome != null)
				return false;
		} else if (!ramNome.equals(other.ramNome))
			return false;
		if (ramObservacao == null) {
			if (other.ramObservacao != null)
				return false;
		} else if (!ramObservacao.equals(other.ramObservacao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Ramoatuacao [ramId=" + ramId + "]";
	}

}
