package br.com.locadora.modelo;

// Generated 12/05/2014 09:59:32 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * Filial generated by hbm2java
 */
@Audited
@Entity
@Table(name = "FILIAL", catalog = "renovarsistemas")
@AuditTable(value="FILIAL", schema="log", catalog="renovarsistemas")
public class Filial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2927694776841866994L;
	private int filId;
	private Endereco endereco;
	private String filNome;
	private String filCnpj;
	private String filObservacao;
	private String filIm;
	private String filIe;
	private Set<Email> emails = new HashSet<Email>(0);
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
	private Set<Telefone> telefones = new HashSet<Telefone>(0);
	private Set<Locacao> locacaos = new HashSet<Locacao>(0);
	private Set<QuadroDeChaves> quadroDeChaveses = new HashSet<QuadroDeChaves>(
			0);
	private Set<Endereco> enderecos = new HashSet<Endereco>(0);

	public Filial() {
	}

	public Filial(int filId, Endereco endereco, String filNome) {
		this.filId = filId;
		this.endereco = endereco;
		this.filNome = filNome;
	}

	public Filial(int filId, Endereco endereco, String filNome, String filCnpj,
			String filObservacao, String filIm, String filIe,
			Set<Email> emails, Set<Funcionario> funcionarios,
			Set<Telefone> telefones, Set<Locacao> locacaos,
			Set<QuadroDeChaves> quadroDeChaveses, Set<Endereco> enderecos) {
		this.filId = filId;
		this.endereco = endereco;
		this.filNome = filNome;
		this.filCnpj = filCnpj;
		this.filObservacao = filObservacao;
		this.filIm = filIm;
		this.filIe = filIe;
		this.emails = emails;
		this.funcionarios = funcionarios;
		this.telefones = telefones;
		this.locacaos = locacaos;
		this.quadroDeChaveses = quadroDeChaveses;
		this.enderecos = enderecos;
	}

	@Id
	@GeneratedValue
	@Column(name = "FIL_ID", unique = true, nullable = false)
	public int getFilId() {
		return this.filId;
	}

	public void setFilId(int filId) {
		this.filId = filId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "END_ID", nullable = false)
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@Column(name = "FIL_NOME", nullable = false, length = 50)
	public String getFilNome() {
		return this.filNome;
	}

	public void setFilNome(String filNome) {
		this.filNome = filNome;
	}

	@Column(name = "FIL_CNPJ", length = 14)
	public String getFilCnpj() {
		return this.filCnpj;
	}

	public void setFilCnpj(String filCnpj) {
		this.filCnpj = filCnpj;
	}

	@Column(name = "FIL_OBSERVACAO", length = 200)
	public String getFilObservacao() {
		return this.filObservacao;
	}

	public void setFilObservacao(String filObservacao) {
		this.filObservacao = filObservacao;
	}

	@Column(name = "FIL_IM", length = 15)
	public String getFilIm() {
		return this.filIm;
	}

	public void setFilIm(String filIm) {
		this.filIm = filIm;
	}

	@Column(name = "FIL_IE", length = 18)
	public String getFilIe() {
		return this.filIe;
	}

	public void setFilIe(String filIe) {
		this.filIe = filIe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	@NotAudited
	public Set<Email> getEmails() {
		return this.emails;
	}

	public void setEmails(Set<Email> emails) {
		this.emails = emails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	@NotAudited
	public Set<Funcionario> getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	@NotAudited
	public Set<Telefone> getTelefones() {
		return this.telefones;
	}

	public void setTelefones(Set<Telefone> telefones) {
		this.telefones = telefones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	@NotAudited
	public Set<Locacao> getLocacaos() {
		return this.locacaos;
	}

	public void setLocacaos(Set<Locacao> locacaos) {
		this.locacaos = locacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	@NotAudited
	public Set<QuadroDeChaves> getQuadroDeChaveses() {
		return this.quadroDeChaveses;
	}

	public void setQuadroDeChaveses(Set<QuadroDeChaves> quadroDeChaveses) {
		this.quadroDeChaveses = quadroDeChaveses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	@NotAudited
	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((emails == null) ? 0 : emails.hashCode());
		result = prime * result
				+ ((endereco == null) ? 0 : endereco.hashCode());
		result = prime * result
				+ ((enderecos == null) ? 0 : enderecos.hashCode());
		result = prime * result + ((filCnpj == null) ? 0 : filCnpj.hashCode());
		result = prime * result + filId;
		result = prime * result + ((filIe == null) ? 0 : filIe.hashCode());
		result = prime * result + ((filIm == null) ? 0 : filIm.hashCode());
		result = prime * result + ((filNome == null) ? 0 : filNome.hashCode());
		result = prime * result
				+ ((filObservacao == null) ? 0 : filObservacao.hashCode());
		result = prime * result
				+ ((funcionarios == null) ? 0 : funcionarios.hashCode());
		result = prime * result
				+ ((locacaos == null) ? 0 : locacaos.hashCode());
		result = prime
				* result
				+ ((quadroDeChaveses == null) ? 0 : quadroDeChaveses.hashCode());
		result = prime * result
				+ ((telefones == null) ? 0 : telefones.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Filial other = (Filial) obj;
		if (emails == null) {
			if (other.emails != null)
				return false;
		} else if (!emails.equals(other.emails))
			return false;
		if (endereco == null) {
			if (other.endereco != null)
				return false;
		} else if (!endereco.equals(other.endereco))
			return false;
		if (enderecos == null) {
			if (other.enderecos != null)
				return false;
		} else if (!enderecos.equals(other.enderecos))
			return false;
		if (filCnpj == null) {
			if (other.filCnpj != null)
				return false;
		} else if (!filCnpj.equals(other.filCnpj))
			return false;
		if (filId != other.filId)
			return false;
		if (filIe == null) {
			if (other.filIe != null)
				return false;
		} else if (!filIe.equals(other.filIe))
			return false;
		if (filIm == null) {
			if (other.filIm != null)
				return false;
		} else if (!filIm.equals(other.filIm))
			return false;
		if (filNome == null) {
			if (other.filNome != null)
				return false;
		} else if (!filNome.equals(other.filNome))
			return false;
		if (filObservacao == null) {
			if (other.filObservacao != null)
				return false;
		} else if (!filObservacao.equals(other.filObservacao))
			return false;
		if (funcionarios == null) {
			if (other.funcionarios != null)
				return false;
		} else if (!funcionarios.equals(other.funcionarios))
			return false;
		if (locacaos == null) {
			if (other.locacaos != null)
				return false;
		} else if (!locacaos.equals(other.locacaos))
			return false;
		if (quadroDeChaveses == null) {
			if (other.quadroDeChaveses != null)
				return false;
		} else if (!quadroDeChaveses.equals(other.quadroDeChaveses))
			return false;
		if (telefones == null) {
			if (other.telefones != null)
				return false;
		} else if (!telefones.equals(other.telefones))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Filial [filId=" + filId + "]";
	}

}
