package br.com.locadora.web;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;





import lombok.Getter;
import lombok.Setter;
import br.com.locadora.modelo.Cidade;
import br.com.locadora.rn.CidadeRN;
import br.com.locadora.web.util.ContextoUtil;

/**
 * Cidade generated by hbm2java
 */
@ManagedBean(name = "cidadeBean")
@ViewScoped
public class CidadeBean implements Serializable{

	/**
	 * 
	 */
	@Getter private static final long serialVersionUID = -7555318516120306587L;
	private Cidade cidade = new Cidade();
	private List<Cidade> listaCidades;
	private String destinoSalvar;
	
	@Getter @Setter private ContextoBean contextoBean=ContextoUtil.getContextoBean();

	public String excluirCidade() {
		CidadeRN cidadeRN = new CidadeRN();
		cidadeRN.excluir(cidade);

		FacesContext context = FacesContext.getCurrentInstance();
		context.addMessage(null, new FacesMessage("Excluido com sucesso"));
		this.listaCidades = null;
		return null;

	}
	



	public String getDestinoSalvar() {
		return destinoSalvar;
	}

	public void setDestinoSalvar(String destinoSalvar) {
		this.destinoSalvar = destinoSalvar;
	}

	public void setListaCidades(List<Cidade> listacid) {
		this.listaCidades = listacid;
	}

	public List<Cidade> getListaCidades() {
		if (this.listaCidades == null) {
			CidadeRN cidadeRN = new CidadeRN();
			this.listaCidades = cidadeRN.listar();
		}
		return this.listaCidades;
	}

	public String editar() {
		return "/publico/cadastrocidade";
	}

	public String salvar() {

		CidadeRN cidadaRN = new CidadeRN();
		if(cidadaRN.buscarPorCidade(cidade.getCidNome())==null){
		cidadaRN.salvar(this.cidade);
		}else {
		//	System.out.println("Já existe a Cidade ! \n");
			 FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL,"Não cadastrado: ", "Está Cidade já Existe no Banco de Dados"));
					}
		
		this.cidade=new Cidade();
		//return this.destinoSalvar;
		this.listaCidades= null;
		return null;
	}

	public Cidade getCidade() {
		return cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

}
