package br.com.locadora.modelo;

// Generated 11/04/2014 14:12:50 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CaracteristicasImovelDesejadoId generated by hbm2java
 */
@Embeddable
public class CaracteristicasImovelDesejadoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -998469435044159878L;
	private int carId;
	private int imoDesId;

	public CaracteristicasImovelDesejadoId() {
	}

	public CaracteristicasImovelDesejadoId(int carId, int imoDesId) {
		this.carId = carId;
		this.imoDesId = imoDesId;
	}

	@Column(name = "CAR_ID", nullable = false)
	public int getCarId() {
		return this.carId;
	}

	public void setCarId(int carId) {
		this.carId = carId;
	}

	@Column(name = "IMO_DES_ID", nullable = false)
	public int getImoDesId() {
		return this.imoDesId;
	}

	public void setImoDesId(int imoDesId) {
		this.imoDesId = imoDesId;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CaracteristicasImovelDesejadoId other = (CaracteristicasImovelDesejadoId) obj;
		if (carId != other.carId)
			return false;
		if (imoDesId != other.imoDesId)
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + carId;
		result = prime * result + imoDesId;
		return result;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "CaracteristicasImovelDesejadoId [carId=" + carId
				+ ", imoDesId=" + imoDesId + "]";
	}



}
