package br.com.locadora.modelo;

// Generated 11/04/2014 14:12:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * QuadroDeChaves generated by hbm2java
 */
@Audited
@Entity
@Table(name = "QUADRO_DE_CHAVES", catalog = "renovarsistemas")
@AuditTable(value="QUADRO_DE_CHAVES", schema="log", catalog="renovarsistemas")
public class QuadroDeChaves implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6021215287160536319L;
	private int quaId;
	private Filial filial;
	private Set<ChaveNoQuadro> chaveNoQuadros = new HashSet<ChaveNoQuadro>(0);

	public QuadroDeChaves() {
	}

	public QuadroDeChaves(int quaId, Filial filial) {
		this.quaId = quaId;
		this.filial = filial;
	}

	public QuadroDeChaves(int quaId, Filial filial,
			Set<ChaveNoQuadro> chaveNoQuadros) {
		this.quaId = quaId;
		this.filial = filial;
		this.chaveNoQuadros = chaveNoQuadros;
	}

	@Id
	@GeneratedValue
	@Column(name = "QUA_ID", unique = true, nullable = false)
	public int getQuaId() {
		return this.quaId;
	}

	public void setQuaId(int quaId) {
		this.quaId = quaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIL_ID", nullable = false)
	public Filial getFilial() {
		return this.filial;
	}

	public void setFilial(Filial filial) {
		this.filial = filial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quadroDeChaves")
	@NotAudited
	public Set<ChaveNoQuadro> getChaveNoQuadros() {
		return this.chaveNoQuadros;
	}

	public void setChaveNoQuadros(Set<ChaveNoQuadro> chaveNoQuadros) {
		this.chaveNoQuadros = chaveNoQuadros;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((chaveNoQuadros == null) ? 0 : chaveNoQuadros.hashCode());
		result = prime * result + ((filial == null) ? 0 : filial.hashCode());
		result = prime * result + quaId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		QuadroDeChaves other = (QuadroDeChaves) obj;
		if (chaveNoQuadros == null) {
			if (other.chaveNoQuadros != null)
				return false;
		} else if (!chaveNoQuadros.equals(other.chaveNoQuadros))
			return false;
		if (filial == null) {
			if (other.filial != null)
				return false;
		} else if (!filial.equals(other.filial))
			return false;
		if (quaId != other.quaId)
			return false;
		return true;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "QuadroDeChaves [quaId=" + quaId + "]";
	}

}
