package br.com.locadora.modelo;

// Generated 26/06/2014 17:19:33 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * PermissoesLocacao generated by hbm2java
 */
@Audited
@Entity
@Table(name = "PERMISSOES_LOCACAO", catalog = "renovarsistemas")
@AuditTable(value="PERMISSOES_LOCACAO", schema="log", catalog="renovarsistemas")
public class PermissoesLocacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3643549760814966092L;
	private int perLocId;
	private String perLocNome;
	private Set<SituacaoLocacaoPermissoes> situacaoLocacaoPermissoeses = new HashSet<SituacaoLocacaoPermissoes>(
			0);

	public PermissoesLocacao() {
	}

	public PermissoesLocacao(int perLocId) {
		this.perLocId = perLocId;
	}

	public PermissoesLocacao(int perLocId, String perLocNome,
			Set<SituacaoLocacaoPermissoes> situacaoLocacaoPermissoeses) {
		this.perLocId = perLocId;
		this.perLocNome = perLocNome;
		this.situacaoLocacaoPermissoeses = situacaoLocacaoPermissoeses;
	}

	@Id
	@GeneratedValue
	@Column(name = "PER_LOC_ID", unique = true, nullable = false)
	public int getPerLocId() {
		return this.perLocId;
	}

	public void setPerLocId(int perLocId) {
		this.perLocId = perLocId;
	}

	@Column(name = "PER_LOC_NOME", length = 70)
	public String getPerLocNome() {
		return this.perLocNome;
	}

	public void setPerLocNome(String perLocNome) {
		this.perLocNome = perLocNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissoesLocacao")
	@NotAudited
	public Set<SituacaoLocacaoPermissoes> getSituacaoLocacaoPermissoeses() {
		return this.situacaoLocacaoPermissoeses;
	}

	public void setSituacaoLocacaoPermissoeses(
			Set<SituacaoLocacaoPermissoes> situacaoLocacaoPermissoeses) {
		this.situacaoLocacaoPermissoeses = situacaoLocacaoPermissoeses;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + perLocId;
		result = prime * result
				+ ((perLocNome == null) ? 0 : perLocNome.hashCode());
		result = prime
				* result
				+ ((situacaoLocacaoPermissoeses == null) ? 0
						: situacaoLocacaoPermissoeses.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PermissoesLocacao other = (PermissoesLocacao) obj;
		if (perLocId != other.perLocId)
			return false;
		if (perLocNome == null) {
			if (other.perLocNome != null)
				return false;
		} else if (!perLocNome.equals(other.perLocNome))
			return false;
		if (situacaoLocacaoPermissoeses == null) {
			if (other.situacaoLocacaoPermissoeses != null)
				return false;
		} else if (!situacaoLocacaoPermissoeses
				.equals(other.situacaoLocacaoPermissoeses))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "PermissoesLocacao [perLocId=" + perLocId + "]";
	}

}
