package br.com.locadora.modelo;

// Generated 25/08/2014 14:40:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * Iptu generated by hbm2java
 */
@Audited
@Entity
@Table(name = "IPTU", catalog = "renovarsistemas")
@AuditTable(value="IPTU", schema="log", catalog="renovarsistemas")
public class Iptu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5299990524405129369L;
	private int iptId;
	private Locacao locacao;
	private Double iptValor;
	private Integer iptParcelas;
	private String iptCodigoReduzido;
	private Integer iptAno;

	public Iptu() {
	}

	public Iptu(int iptId, Locacao locacao) {
		this.iptId = iptId;
		this.locacao = locacao;
	}

	public Iptu(int iptId, Locacao locacao, Double iptValor,
			Integer iptParcelas, String iptCodigoReduzido, Integer iptAno) {
		this.iptId = iptId;
		this.locacao = locacao;
		this.iptValor = iptValor;
		this.iptParcelas = iptParcelas;
		this.iptCodigoReduzido = iptCodigoReduzido;
		this.iptAno = iptAno;
	}

	@Id
	@GeneratedValue
	@Column(name = "IPT_ID", unique = true, nullable = false)
	public int getIptId() {
		return this.iptId;
	}

	public void setIptId(int iptId) {
		this.iptId = iptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOC_ID", nullable = false)
	public Locacao getLocacao() {
		return this.locacao;
	}

	public void setLocacao(Locacao locacao) {
		this.locacao = locacao;
	}

	@Column(name = "IPT_VALOR", precision = 53, scale = 0)
	public Double getIptValor() {
		return this.iptValor;
	}

	public void setIptValor(Double iptValor) {
		this.iptValor = iptValor;
	}

	@Column(name = "IPT_PARCELAS")
	public Integer getIptParcelas() {
		return this.iptParcelas;
	}

	public void setIptParcelas(Integer iptParcelas) {
		this.iptParcelas = iptParcelas;
	}

	@Column(name = "IPT_CODIGO_REDUZIDO", length = 50)
	public String getIptCodigoReduzido() {
		return this.iptCodigoReduzido;
	}

	public void setIptCodigoReduzido(String iptCodigoReduzido) {
		this.iptCodigoReduzido = iptCodigoReduzido;
	}

	@Column(name = "IPT_ANO")
	public Integer getIptAno() {
		return this.iptAno;
	}

	public void setIptAno(Integer iptAno) {
		this.iptAno = iptAno;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((iptAno == null) ? 0 : iptAno.hashCode());
		result = prime
				* result
				+ ((iptCodigoReduzido == null) ? 0 : iptCodigoReduzido
						.hashCode());
		result = prime * result + iptId;
		result = prime * result
				+ ((iptParcelas == null) ? 0 : iptParcelas.hashCode());
		result = prime * result
				+ ((iptValor == null) ? 0 : iptValor.hashCode());
		result = prime * result + ((locacao == null) ? 0 : locacao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Iptu other = (Iptu) obj;
		if (iptAno == null) {
			if (other.iptAno != null)
				return false;
		} else if (!iptAno.equals(other.iptAno))
			return false;
		if (iptCodigoReduzido == null) {
			if (other.iptCodigoReduzido != null)
				return false;
		} else if (!iptCodigoReduzido.equals(other.iptCodigoReduzido))
			return false;
		if (iptId != other.iptId)
			return false;
		if (iptParcelas == null) {
			if (other.iptParcelas != null)
				return false;
		} else if (!iptParcelas.equals(other.iptParcelas))
			return false;
		if (iptValor == null) {
			if (other.iptValor != null)
				return false;
		} else if (!iptValor.equals(other.iptValor))
			return false;
		if (locacao == null) {
			if (other.locacao != null)
				return false;
		} else if (!locacao.equals(other.locacao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Iptu [iptId=" + iptId + "]";
	}

}
