package br.com.locadora.modelo;

// Generated 11/04/2014 14:12:50 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChaveNoQuadroId generated by hbm2java
 */
@Embeddable
public class ChaveNoQuadroId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5303391842565514935L;
	private int imoId;
	private int quaId;

	public ChaveNoQuadroId() {
	}

	public ChaveNoQuadroId(int imoId, int quaId) {
		this.imoId = imoId;
		this.quaId = quaId;
	}

	@Column(name = "IMO_ID", nullable = false)
	public int getImoId() {
		return this.imoId;
	}

	public void setImoId(int imoId) {
		this.imoId = imoId;
	}

	@Column(name = "QUA_ID", nullable = false)
	public int getQuaId() {
		return this.quaId;
	}

	public void setQuaId(int quaId) {
		this.quaId = quaId;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChaveNoQuadroId other = (ChaveNoQuadroId) obj;
		if (imoId != other.imoId)
			return false;
		if (quaId != other.quaId)
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + imoId;
		result = prime * result + quaId;
		return result;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "ChaveNoQuadroId [imoId=" + imoId + ", quaId=" + quaId + "]";
	}



}
