package br.com.locadora.modelo;

// Generated 17/07/2014 11:39:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * SeguroIncendioImovelResidencial generated by hbm2java
 */
@Audited
@Entity
@Table(name = "SEGURO_INCENDIO_IMOVEL_RESIDENCIAL", catalog = "renovarsistemas")
@AuditTable(value="SEGURO_INCENDIO_IMOVEL_RESIDENCIAL", schema="log", catalog="renovarsistemas")
public class SeguroIncendioImovelResidencial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3714580430669896866L;
	private int segIncImoResId;
	private Double segIncImoResValorVenal;
	private Double segIncImoResPerdaAluguel;
	private Double segIncImoResTotalCusto;

	public SeguroIncendioImovelResidencial() {
	}

	public SeguroIncendioImovelResidencial(int segIncImoResId) {
		this.segIncImoResId = segIncImoResId;
	}

	public SeguroIncendioImovelResidencial(int segIncImoResId,
			Double segIncImoResValorVenal, Double segIncImoResPerdaAluguel,
			Double segIncImoResTotalCusto) {
		this.segIncImoResId = segIncImoResId;
		this.segIncImoResValorVenal = segIncImoResValorVenal;
		this.segIncImoResPerdaAluguel = segIncImoResPerdaAluguel;
		this.segIncImoResTotalCusto = segIncImoResTotalCusto;
	}

	@Id
	@GeneratedValue
	@Column(name = "SEG_INC_IMO_RES_ID", unique = true, nullable = false)
	public int getSegIncImoResId() {
		return this.segIncImoResId;
	}

	public void setSegIncImoResId(int segIncImoResId) {
		this.segIncImoResId = segIncImoResId;
	}

	@Column(name = "SEG_INC_IMO_RES_VALOR_VENAL", precision = 53, scale = 0)
	public Double getSegIncImoResValorVenal() {
		return this.segIncImoResValorVenal;
	}

	public void setSegIncImoResValorVenal(Double segIncImoResValorVenal) {
		this.segIncImoResValorVenal = segIncImoResValorVenal;
	}

	@Column(name = "SEG_INC_IMO_RES_PERDA_ALUGUEL", precision = 53, scale = 0)
	public Double getSegIncImoResPerdaAluguel() {
		return this.segIncImoResPerdaAluguel;
	}

	public void setSegIncImoResPerdaAluguel(Double segIncImoResPerdaAluguel) {
		this.segIncImoResPerdaAluguel = segIncImoResPerdaAluguel;
	}

	@Column(name = "SEG_INC_IMO_RES_TOTAL_CUSTO", precision = 53, scale = 0)
	public Double getSegIncImoResTotalCusto() {
		return this.segIncImoResTotalCusto;
	}

	public void setSegIncImoResTotalCusto(Double segIncImoResTotalCusto) {
		this.segIncImoResTotalCusto = segIncImoResTotalCusto;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + segIncImoResId;
		result = prime
				* result
				+ ((segIncImoResPerdaAluguel == null) ? 0
						: segIncImoResPerdaAluguel.hashCode());
		result = prime
				* result
				+ ((segIncImoResTotalCusto == null) ? 0
						: segIncImoResTotalCusto.hashCode());
		result = prime
				* result
				+ ((segIncImoResValorVenal == null) ? 0
						: segIncImoResValorVenal.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SeguroIncendioImovelResidencial other = (SeguroIncendioImovelResidencial) obj;
		if (segIncImoResId != other.segIncImoResId)
			return false;
		if (segIncImoResPerdaAluguel == null) {
			if (other.segIncImoResPerdaAluguel != null)
				return false;
		} else if (!segIncImoResPerdaAluguel
				.equals(other.segIncImoResPerdaAluguel))
			return false;
		if (segIncImoResTotalCusto == null) {
			if (other.segIncImoResTotalCusto != null)
				return false;
		} else if (!segIncImoResTotalCusto.equals(other.segIncImoResTotalCusto))
			return false;
		if (segIncImoResValorVenal == null) {
			if (other.segIncImoResValorVenal != null)
				return false;
		} else if (!segIncImoResValorVenal.equals(other.segIncImoResValorVenal))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "SeguroIncendioImovelResidencial [segIncImoResId="
				+ segIncImoResId + "]";
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
