package br.com.locadora.modelo;

// Generated 15/09/2014 11:39:54 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * ContasAPagar generated by hbm2java
 */
@Entity
@Audited
@Table(name = "CONTAS_A_PAGAR", catalog = "renovarsistemas")
@AuditTable(value="CONTAS_A_PAGAR", schema="log", catalog="renovarsistemas")
public class ContasAPagar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7044420126696781424L;
	private int conPagId;
	private Double conPagValor;
	private Date conPagDataCadastro;
	private Date conPagDataVencimento;
	private String conPagTipoMovimentacao;
	private String conPagHistorico;
	private String conPagObservacao;
	private Integer conPagIdContrato;
	private Integer conPagGrupoDeContas;
	private Set<LancamentoContasAPagar> lancamentoContasAPagars = new HashSet<LancamentoContasAPagar>(
			0);

	public ContasAPagar() {
	}

	public ContasAPagar(int conPagId) {
		this.conPagId = conPagId;
	}

	public ContasAPagar(int conPagId, Double conPagValor,
			Date conPagDataCadastro, Date conPagDataVencimento,
			String conPagTipoMovimentacao, String conPagHistorico,
			String conPagObservacao, Integer conPagIdContrato,
			Integer conPagGrupoDeContas,
			Set<LancamentoContasAPagar> lancamentoContasAPagars) {
		this.conPagId = conPagId;
		this.conPagValor = conPagValor;
		this.conPagDataCadastro = conPagDataCadastro;
		this.conPagDataVencimento = conPagDataVencimento;
		this.conPagTipoMovimentacao = conPagTipoMovimentacao;
		this.conPagHistorico = conPagHistorico;
		this.conPagObservacao = conPagObservacao;
		this.conPagIdContrato = conPagIdContrato;
		this.conPagGrupoDeContas = conPagGrupoDeContas;
		this.lancamentoContasAPagars = lancamentoContasAPagars;
	}

	@Id
	@GeneratedValue
	@Column(name = "CON_PAG_ID", unique = true, nullable = false)
	public int getConPagId() {
		return this.conPagId;
	}

	public void setConPagId(int conPagId) {
		this.conPagId = conPagId;
	}

	@Column(name = "CON_PAG_VALOR", precision = 53, scale = 0)
	public Double getConPagValor() {
		return this.conPagValor;
	}

	public void setConPagValor(Double conPagValor) {
		this.conPagValor = conPagValor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CON_PAG_DATA_CADASTRO", length = 23)
	public Date getConPagDataCadastro() {
		return this.conPagDataCadastro;
	}

	public void setConPagDataCadastro(Date conPagDataCadastro) {
		this.conPagDataCadastro = conPagDataCadastro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CON_PAG_DATA_VENCIMENTO", length = 23)
	public Date getConPagDataVencimento() {
		return this.conPagDataVencimento;
	}

	public void setConPagDataVencimento(Date conPagDataVencimento) {
		this.conPagDataVencimento = conPagDataVencimento;
	}

	@Column(name = "CON_PAG_TIPO_MOVIMENTACAO", length = 70)
	public String getConPagTipoMovimentacao() {
		return this.conPagTipoMovimentacao;
	}

	public void setConPagTipoMovimentacao(String conPagTipoMovimentacao) {
		this.conPagTipoMovimentacao = conPagTipoMovimentacao;
	}

	@Column(name = "CON_PAG_HISTORICO", length = 251)
	public String getConPagHistorico() {
		return this.conPagHistorico;
	}

	public void setConPagHistorico(String conPagHistorico) {
		this.conPagHistorico = conPagHistorico;
	}

	@Column(name = "CON_PAG_OBSERVACAO", length = 200)
	public String getConPagObservacao() {
		return this.conPagObservacao;
	}

	public void setConPagObservacao(String conPagObservacao) {
		this.conPagObservacao = conPagObservacao;
	}

	@Column(name = "CON_PAG_ID_CONTRATO")
	public Integer getConPagIdContrato() {
		return this.conPagIdContrato;
	}

	public void setConPagIdContrato(Integer conPagIdContrato) {
		this.conPagIdContrato = conPagIdContrato;
	}

	@Column(name = "CON_PAG_GRUPO_DE_CONTAS")
	public Integer getConPagGrupoDeContas() {
		return this.conPagGrupoDeContas;
	}

	public void setConPagGrupoDeContas(Integer conPagGrupoDeContas) {
		this.conPagGrupoDeContas = conPagGrupoDeContas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contasAPagar")
	@NotAudited
	public Set<LancamentoContasAPagar> getLancamentoContasAPagars() {
		return this.lancamentoContasAPagars;
	}

	public void setLancamentoContasAPagars(
			Set<LancamentoContasAPagar> lancamentoContasAPagars) {
		this.lancamentoContasAPagars = lancamentoContasAPagars;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((conPagDataCadastro == null) ? 0 : conPagDataCadastro
						.hashCode());
		result = prime
				* result
				+ ((conPagDataVencimento == null) ? 0 : conPagDataVencimento
						.hashCode());
		result = prime
				* result
				+ ((conPagGrupoDeContas == null) ? 0 : conPagGrupoDeContas
						.hashCode());
		result = prime * result
				+ ((conPagHistorico == null) ? 0 : conPagHistorico.hashCode());
		result = prime * result + conPagId;
		result = prime
				* result
				+ ((conPagIdContrato == null) ? 0 : conPagIdContrato.hashCode());
		result = prime
				* result
				+ ((conPagObservacao == null) ? 0 : conPagObservacao.hashCode());
		result = prime
				* result
				+ ((conPagTipoMovimentacao == null) ? 0
						: conPagTipoMovimentacao.hashCode());
		result = prime * result
				+ ((conPagValor == null) ? 0 : conPagValor.hashCode());
		result = prime
				* result
				+ ((lancamentoContasAPagars == null) ? 0
						: lancamentoContasAPagars.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ContasAPagar other = (ContasAPagar) obj;
		if (conPagDataCadastro == null) {
			if (other.conPagDataCadastro != null)
				return false;
		} else if (!conPagDataCadastro.equals(other.conPagDataCadastro))
			return false;
		if (conPagDataVencimento == null) {
			if (other.conPagDataVencimento != null)
				return false;
		} else if (!conPagDataVencimento.equals(other.conPagDataVencimento))
			return false;
		if (conPagGrupoDeContas == null) {
			if (other.conPagGrupoDeContas != null)
				return false;
		} else if (!conPagGrupoDeContas.equals(other.conPagGrupoDeContas))
			return false;
		if (conPagHistorico == null) {
			if (other.conPagHistorico != null)
				return false;
		} else if (!conPagHistorico.equals(other.conPagHistorico))
			return false;
		if (conPagId != other.conPagId)
			return false;
		if (conPagIdContrato == null) {
			if (other.conPagIdContrato != null)
				return false;
		} else if (!conPagIdContrato.equals(other.conPagIdContrato))
			return false;
		if (conPagObservacao == null) {
			if (other.conPagObservacao != null)
				return false;
		} else if (!conPagObservacao.equals(other.conPagObservacao))
			return false;
		if (conPagTipoMovimentacao == null) {
			if (other.conPagTipoMovimentacao != null)
				return false;
		} else if (!conPagTipoMovimentacao.equals(other.conPagTipoMovimentacao))
			return false;
		if (conPagValor == null) {
			if (other.conPagValor != null)
				return false;
		} else if (!conPagValor.equals(other.conPagValor))
			return false;
		if (lancamentoContasAPagars == null) {
			if (other.lancamentoContasAPagars != null)
				return false;
		} else if (!lancamentoContasAPagars
				.equals(other.lancamentoContasAPagars))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ContasAPagar [conPagId=" + conPagId + "]";
	}

}
