package br.com.locadora.modelo;

// Generated 17/07/2014 11:39:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * SeguroIncendioImovelComercial generated by hbm2java
 */
@Audited
@Entity
@Table(name = "SEGURO_INCENDIO_IMOVEL_COMERCIAL", catalog = "renovarsistemas")
@AuditTable(value="SEGURO_INCENDIO_IMOVEL_COMERCIAL", schema="log", catalog="renovarsistemas")
public class SeguroIncendioImovelComercial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1833194654371970324L;
	private int segIncImoComId;
	private Double segIncImoComValorVenal;
	private Double segIncImoComPerdaAluguel;
	private Double segIncImoComTotalCusto;

	public SeguroIncendioImovelComercial() {
	}

	public SeguroIncendioImovelComercial(int segIncImoComId) {
		this.segIncImoComId = segIncImoComId;
	}

	public SeguroIncendioImovelComercial(int segIncImoComId,
			Double segIncImoComValorVenal, Double segIncImoComPerdaAluguel,
			Double segIncImoComTotalCusto) {
		this.segIncImoComId = segIncImoComId;
		this.segIncImoComValorVenal = segIncImoComValorVenal;
		this.segIncImoComPerdaAluguel = segIncImoComPerdaAluguel;
		this.segIncImoComTotalCusto = segIncImoComTotalCusto;
	}

	@Id
	@GeneratedValue
	@Column(name = "SEG_INC_IMO_COM_ID", unique = true, nullable = false)
	public int getSegIncImoComId() {
		return this.segIncImoComId;
	}

	public void setSegIncImoComId(int segIncImoComId) {
		this.segIncImoComId = segIncImoComId;
	}

	@Column(name = "SEG_INC_IMO_COM_VALOR_VENAL", precision = 53, scale = 0)
	public Double getSegIncImoComValorVenal() {
		return this.segIncImoComValorVenal;
	}

	public void setSegIncImoComValorVenal(Double segIncImoComValorVenal) {
		this.segIncImoComValorVenal = segIncImoComValorVenal;
	}

	@Column(name = "SEG_INC_IMO_COM_PERDA_ALUGUEL", precision = 53, scale = 0)
	public Double getSegIncImoComPerdaAluguel() {
		return this.segIncImoComPerdaAluguel;
	}

	public void setSegIncImoComPerdaAluguel(Double segIncImoComPerdaAluguel) {
		this.segIncImoComPerdaAluguel = segIncImoComPerdaAluguel;
	}

	@Column(name = "SEG_INC_IMO_COM_TOTAL_CUSTO", precision = 53, scale = 0)
	public Double getSegIncImoComTotalCusto() {
		return this.segIncImoComTotalCusto;
	}

	public void setSegIncImoComTotalCusto(Double segIncImoComTotalCusto) {
		this.segIncImoComTotalCusto = segIncImoComTotalCusto;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + segIncImoComId;
		result = prime
				* result
				+ ((segIncImoComPerdaAluguel == null) ? 0
						: segIncImoComPerdaAluguel.hashCode());
		result = prime
				* result
				+ ((segIncImoComTotalCusto == null) ? 0
						: segIncImoComTotalCusto.hashCode());
		result = prime
				* result
				+ ((segIncImoComValorVenal == null) ? 0
						: segIncImoComValorVenal.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SeguroIncendioImovelComercial other = (SeguroIncendioImovelComercial) obj;
		if (segIncImoComId != other.segIncImoComId)
			return false;
		if (segIncImoComPerdaAluguel == null) {
			if (other.segIncImoComPerdaAluguel != null)
				return false;
		} else if (!segIncImoComPerdaAluguel
				.equals(other.segIncImoComPerdaAluguel))
			return false;
		if (segIncImoComTotalCusto == null) {
			if (other.segIncImoComTotalCusto != null)
				return false;
		} else if (!segIncImoComTotalCusto.equals(other.segIncImoComTotalCusto))
			return false;
		if (segIncImoComValorVenal == null) {
			if (other.segIncImoComValorVenal != null)
				return false;
		} else if (!segIncImoComValorVenal.equals(other.segIncImoComValorVenal))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "SeguroIncendioImovelComercial [segIncImoComId="
				+ segIncImoComId + "]";
	}

}
