package br.com.locadora.modelo;

// Generated 04/09/2014 15:47:45 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * Parametro generated by hbm2java
 */
@Audited
@Entity
@Table(name = "PARAMETRO", catalog = "renovarsistemas")
@AuditTable(value="PARAMETRO", schema="log", catalog="renovarsistemas")
public class Parametro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6607898155381280692L;
	private int parId;
	private String parNome;
	private Set<TipoDeParametro> tipoDeParametros = new HashSet<TipoDeParametro>(
			0);

	public Parametro() {
	}

	public Parametro(int parId) {
		this.parId = parId;
	}

	public Parametro(int parId, String parNome,
			Set<TipoDeParametro> tipoDeParametros) {
		this.parId = parId;
		this.parNome = parNome;
		this.tipoDeParametros = tipoDeParametros;
	}

	@Id
	@GeneratedValue
	@Column(name = "PAR_ID", unique = true, nullable = false)
	public int getParId() {
		return this.parId;
	}

	public void setParId(int parId) {
		this.parId = parId;
	}

	@Column(name = "PAR_NOME", length = 90)
	public String getParNome() {
		return this.parNome;
	}

	public void setParNome(String parNome) {
		this.parNome = parNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parametro")
	@NotAudited
	public Set<TipoDeParametro> getTipoDeParametros() {
		return this.tipoDeParametros;
	}

	public void setTipoDeParametros(Set<TipoDeParametro> tipoDeParametros) {
		this.tipoDeParametros = tipoDeParametros;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + parId;
		result = prime * result + ((parNome == null) ? 0 : parNome.hashCode());
		result = prime
				* result
				+ ((tipoDeParametros == null) ? 0 : tipoDeParametros.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Parametro other = (Parametro) obj;
		if (parId != other.parId)
			return false;
		if (parNome == null) {
			if (other.parNome != null)
				return false;
		} else if (!parNome.equals(other.parNome))
			return false;
		if (tipoDeParametros == null) {
			if (other.tipoDeParametros != null)
				return false;
		} else if (!tipoDeParametros.equals(other.tipoDeParametros))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Parametro [parId=" + parId + "]";
	}

}
