package br.com.locadora.modelo;

// Generated 04/09/2014 15:47:45 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TipoDeParametroId generated by hbm2java
 */
@Embeddable
public class TipoDeParametroId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4620393181716011743L;
	private int parRefId;
	private int parId;

	public TipoDeParametroId() {
	}

	public TipoDeParametroId(int parRefId, int parId) {
		this.parRefId = parRefId;
		this.parId = parId;
	}

	@Column(name = "PAR_REF_ID", nullable = false)
	public int getParRefId() {
		return this.parRefId;
	}

	public void setParRefId(int parRefId) {
		this.parRefId = parRefId;
	}

	@Column(name = "PAR_ID", nullable = false)
	public int getParId() {
		return this.parId;
	}

	public void setParId(int parId) {
		this.parId = parId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoDeParametroId))
			return false;
		TipoDeParametroId castOther = (TipoDeParametroId) other;

		return (this.getParRefId() == castOther.getParRefId())
				&& (this.getParId() == castOther.getParId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getParRefId();
		result = 37 * result + this.getParId();
		return result;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "TipoDeParametroId [parRefId=" + parRefId + ", parId=" + parId
				+ "]";
	}

}
