package br.com.locadora.modelo;

// Generated 27/06/2014 14:13:48 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * ValorIndiceReajuste generated by hbm2java
 */
@Audited
@Entity
@Table(name = "VALOR_INDICE_REAJUSTE", catalog = "renovarsistemas")
@AuditTable(value="VALOR_INDICE_REAJUSTE", schema="log", catalog="renovarsistemas")
public class ValorIndiceReajuste implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3270010528704901948L;
	private int valIndReaId;
	private IndicesReajustes indicesReajustes;
	private Double valIndReaValor;
	private Boolean valIndReaMoeda;
	private Boolean valIndReaIndice;
	private Date valIndReaData;

	public ValorIndiceReajuste() {
	}

	public ValorIndiceReajuste(int valIndReaId,
			IndicesReajustes indicesReajustes) {
		this.valIndReaId = valIndReaId;
		this.indicesReajustes = indicesReajustes;
	}

	public ValorIndiceReajuste(int valIndReaId,
			IndicesReajustes indicesReajustes, Double valIndReaValor,
			Boolean valIndReaMoeda, Boolean valIndReaIndice, Date valIndReaData) {
		this.valIndReaId = valIndReaId;
		this.indicesReajustes = indicesReajustes;
		this.valIndReaValor = valIndReaValor;
		this.valIndReaMoeda = valIndReaMoeda;
		this.valIndReaIndice = valIndReaIndice;
		this.valIndReaData=valIndReaData;
	}

	@Id
	@GeneratedValue
	@Column(name = "VAL_IND_REA_ID", unique = true, nullable = false)
	public int getValIndReaId() {
		return this.valIndReaId;
	}

	public void setValIndReaId(int valIndReaId) {
		this.valIndReaId = valIndReaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IND_REA_ID", nullable = false)
	public IndicesReajustes getIndicesReajustes() {
		return this.indicesReajustes;
	}

	public void setIndicesReajustes(IndicesReajustes indicesReajustes) {
		this.indicesReajustes = indicesReajustes;
	}

	@Column(name = "VAL_IND_REA_VALOR", precision = 53, scale = 0)
	public Double getValIndReaValor() {
		return this.valIndReaValor;
	}

	public void setValIndReaValor(Double valIndReaValor) {
		this.valIndReaValor = valIndReaValor;
	}

	@Column(name = "VAL_IND_REA_MOEDA")
	public Boolean getValIndReaMoeda() {
		return this.valIndReaMoeda;
	}

	public void setValIndReaMoeda(Boolean valIndReaMoeda) {
		this.valIndReaMoeda = valIndReaMoeda;
	}

	@Column(name = "VAL_IND_REA_INDICE")
	public Boolean getValIndReaIndice() {
		return this.valIndReaIndice;
	}

	public void setValIndReaIndice(Boolean valIndReaIndice) {
		this.valIndReaIndice = valIndReaIndice;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VAL_IND_REA_DATA", length = 23)
	public Date getValIndReaData() {
		return this.valIndReaData;
	}

	public void setValIndReaData(Date valIndReaData) {
		this.valIndReaData = valIndReaData;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((indicesReajustes == null) ? 0 : indicesReajustes.hashCode());
		result = prime * result
				+ ((valIndReaData == null) ? 0 : valIndReaData.hashCode());
		result = prime * result + valIndReaId;
		result = prime * result
				+ ((valIndReaIndice == null) ? 0 : valIndReaIndice.hashCode());
		result = prime * result
				+ ((valIndReaMoeda == null) ? 0 : valIndReaMoeda.hashCode());
		result = prime * result
				+ ((valIndReaValor == null) ? 0 : valIndReaValor.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ValorIndiceReajuste other = (ValorIndiceReajuste) obj;
		if (indicesReajustes == null) {
			if (other.indicesReajustes != null)
				return false;
		} else if (!indicesReajustes.equals(other.indicesReajustes))
			return false;
		if (valIndReaData == null) {
			if (other.valIndReaData != null)
				return false;
		} else if (!valIndReaData.equals(other.valIndReaData))
			return false;
		if (valIndReaId != other.valIndReaId)
			return false;
		if (valIndReaIndice == null) {
			if (other.valIndReaIndice != null)
				return false;
		} else if (!valIndReaIndice.equals(other.valIndReaIndice))
			return false;
		if (valIndReaMoeda == null) {
			if (other.valIndReaMoeda != null)
				return false;
		} else if (!valIndReaMoeda.equals(other.valIndReaMoeda))
			return false;
		if (valIndReaValor == null) {
			if (other.valIndReaValor != null)
				return false;
		} else if (!valIndReaValor.equals(other.valIndReaValor))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ValorIndiceReajuste [valIndReaId=" + valIndReaId + "]";
	}

}
