package br.com.locadora.modelo;

// Generated 27/06/2014 14:13:48 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * IndicesReajustes generated by hbm2java
 */
@Audited
@Entity
@Table(name = "INDICES_REAJUSTES", catalog = "renovarsistemas")
@AuditTable(value="INDICES_REAJUSTES", schema="log", catalog="renovarsistemas")
public class IndicesReajustes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 508001066227994154L;
	private int indReaId;
	private String indReaNome;
	private Set<ValorIndiceReajuste> valorIndiceReajustes = new HashSet<ValorIndiceReajuste>(
			0);
	private Set<Locacao> locacaos = new HashSet<Locacao>(0);

	public IndicesReajustes() {
	}

	public IndicesReajustes(int indReaId) {
		this.indReaId = indReaId;
	}

	public IndicesReajustes(int indReaId, String indReaNome,
			Set<ValorIndiceReajuste> valorIndiceReajustes, Set<Locacao> locacaos) {
		this.indReaId = indReaId;
		this.indReaNome = indReaNome;
		this.valorIndiceReajustes = valorIndiceReajustes;
		this.locacaos = locacaos;
	}

	@Id
	@GeneratedValue
	@Column(name = "IND_REA_ID", unique = true, nullable = false)
	public int getIndReaId() {
		return this.indReaId;
	}

	public void setIndReaId(int indReaId) {
		this.indReaId = indReaId;
	}

	@Column(name = "IND_REA_NOME", length = 70)
	public String getIndReaNome() {
		return this.indReaNome;
	}

	public void setIndReaNome(String indReaNome) {
		this.indReaNome = indReaNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indicesReajustes")
	@NotAudited
	public Set<ValorIndiceReajuste> getValorIndiceReajustes() {
		return this.valorIndiceReajustes;
	}

	public void setValorIndiceReajustes(
			Set<ValorIndiceReajuste> valorIndiceReajustes) {
		this.valorIndiceReajustes = valorIndiceReajustes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indicesReajustes")
	@NotAudited
	public Set<Locacao> getLocacaos() {
		return this.locacaos;
	}

	public void setLocacaos(Set<Locacao> locacaos) {
		this.locacaos = locacaos;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + indReaId;
		result = prime * result
				+ ((indReaNome == null) ? 0 : indReaNome.hashCode());
		result = prime * result
				+ ((locacaos == null) ? 0 : locacaos.hashCode());
		result = prime
				* result
				+ ((valorIndiceReajustes == null) ? 0 : valorIndiceReajustes
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		IndicesReajustes other = (IndicesReajustes) obj;
		if (indReaId != other.indReaId)
			return false;
		if (indReaNome == null) {
			if (other.indReaNome != null)
				return false;
		} else if (!indReaNome.equals(other.indReaNome))
			return false;
		if (locacaos == null) {
			if (other.locacaos != null)
				return false;
		} else if (!locacaos.equals(other.locacaos))
			return false;
		if (valorIndiceReajustes == null) {
			if (other.valorIndiceReajustes != null)
				return false;
		} else if (!valorIndiceReajustes.equals(other.valorIndiceReajustes))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "IndicesReajustes [indReaId=" + indReaId + "]";
	}

}
